#!/usr/bin/env python3
"""Bootstrap DB minimal: utilise Oracle si configuré, sinon SQLite local.

Usage: python scripts/bootstrap_db.py
"""
import os
import sys
import logging

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")


def bootstrap_sqlite(path="data.db"):
    import sqlite3

    logging.info("Using SQLite fallback: %s", path)
    conn = sqlite3.connect(path)
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS trades (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL,
            qty INTEGER,
            price REAL,
            ts TEXT
        )
        """
    )
    conn.commit()
    conn.close()
    logging.info("SQLite DB initialized at %s", path)


def bootstrap_oracle():
    try:
        import oracledb
    except Exception as e:
        logging.error("python-oracledb not installed: %s", e)
        return False

    user = os.environ.get("ORACLE_USER")
    password = os.environ.get("ORACLE_PASSWORD")
    dsn = os.environ.get("ORACLE_DSN")
    wallet = os.environ.get("ORACLE_WALLET_PATH")
    wallet_pw = os.environ.get("ORACLE_WALLET_PASSWORD")

    if not (user and password and dsn and wallet):
        logging.error("Missing one of ORACLE_USER/ORACLE_PASSWORD/ORACLE_DSN/ORACLE_WALLET_PATH")
        return False

    logging.info("Connecting to Oracle (thin mode) using wallet at %s", wallet)
    conn = oracledb.connect(
        user=user,
        password=password,
        dsn=dsn,
        wallet_location=wallet,
        wallet_password=wallet_pw,
    )

    cur = conn.cursor()
    cur.execute(
        """
        BEGIN
            EXECUTE IMMEDIATE 'CREATE TABLE trades (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                symbol VARCHAR2(50),
                qty NUMBER,
                price NUMBER,
                ts TIMESTAMP
            )';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """
    )
    conn.commit()
    cur.close()
    conn.close()
    logging.info("Oracle DB initialized (table trades)")
    return True


def main():
    # Prefer Oracle when variables present
    if os.environ.get("ORACLE_USER"):
        try:
            ok = bootstrap_oracle()
            if ok:
                return 0
        except Exception as e:
            logging.error("Oracle bootstrap failed: %s", e)

    # Fallback
    bootstrap_sqlite(path=os.path.join(os.path.dirname(__file__), "..", "data.db"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
